# Git
alias gs="git status"
alias gd="git diff"
alias gds="git diff --staged"
alias ga="git add"
alias gap="git add -p"
alias gco="git checkout"
alias gb="git branch"
alias gcm="git commit -m"
alias gl="git log"
alias gr="git reset"
alias grh="git reset --hard"
alias gst="git stash"

# Misc
alias see="less"
alias du="du -h"
alias df="diff"
alias fs="ls -tr"
alias dd="rm"
